# 제어 흐름과 오류 처리

## 블록문

- 가장 기본적인 명령문은, 명령문들을 그룹으로 묶을 수 있는 **블록문**입니다. 블록문의 블록은 한 쌍의 중괄호로 감싸는 것으로 나타냅니다.


  ```
  {
    statement_1;
    statement_2;
    ⋮
    statement_n;
  }
  ```

  ### 예제

- 블록문은 제어 흐름 명령문과 많이 사용합니다. (`if`, `for`, `while`)

  ```
  while (x < 10) {
    x++;
  }
  ```

- 여기서 `{ x++; }`가 블록문입니다.

## 조건문

### `if...else` 문

- 모범 사례

- 일반적으로는 `if`에 항상, 특히 `if` 문을 중첩할 때는 블록문을 함께 사용하는 것이 좋습니다.


  ```
  if (condition) {
    statement_1_runs_if_condition_is_true;
    statement_2_runs_if_condition_is_true;
  } else {
    statement_3_runs_if_condition_is_false;
    statement_4_runs_if_condition_is_false;
  }  
  ```

### 거짓 값

- 다음 값은 `false`로 평가됩니다. ([거짓](https://developer.mozilla.org/ko/docs/Glossary/Falsy) 값이라고 부릅니다)
  - `false`
  - `undefined`
  - `null`
  - `0`
  - `NaN`
  - 빈 문자열 (`""`)
- 객체를 포함해 다른 모든 값은 조건문에 전달했을 때 `true`로 평가됩니다.

### `switch` 문

- `switch` 문은 프로그램이 표현식을 평가한 후, 그 값과 `case` 레이블의 값을 비교해 일치하는 `case`의 명령문을 실행합니다.

  `switch` 문의 모습은 다음과 같습니다.
```
  switch (expression) {
    case label_1:
      statements_1;
      break;
    case label_2:
      statements_2;
      break;
      …
    default:
      statements_default;
  }
```

- JavaScript는 위의 `switch` 문을 다음의 과정으로 평가합니다.

  - 우선 표현식(`expression`)의 결과와 일치하는 레이블을 가진 `case` 절을 찾아, 관련된 명령문을 실행합니다.

  - 일치하는 레이블을 찾지 못했으면`default`절을 탐색합니다.

    - `default` 절을 찾았으면 관련된 명령문을 실행합니다.
    - `default` 절을 찾지 못했으면 `switch` 문 바깥의 다음 명령문을 실행합니다.
    - (`default`를 마지막에 배치하는 것은 관습적인 것으로, 사실 위치는 상관 없습니다.)

## 예외 유형

### `throw` 문

- 예외를 던질 땐 `throw` 문을 사용하세요. `throw`에 던질 값을 지정하면 됩니다.

```
throw expression;
```

- 특정 타입의 표현식이 아니라 무엇이든 던질 수 있습니다. 아래 코드에서 다양한 타입을 예외로 던지는 모습을 볼 수 있습니다.

```
throw 'Error2'; // String
throw 42; // Number
throw true; // Boolean
throw {
  toString: function () {
    return '저는 객체예요';
  },
};
```

### `try...catch` 문

- `try...catch` 문은 실행을 시도할 블록을 표시하고, 그 안에서 예외가 발생할 경우 처리를 맡을 하나 이상의 반응 명령문을 지정합니다. 예외가 발생하면, `try...catch` 문이 잡아냅니다.

- `try...catch` 문은 하나 이상의 명령문을 포함하는 `try` 블록, 그리고 `try`에서 예외가 발생할 경우 그 예외를 처리할 명령문을 담은 하나의 `catch` 블록으로 구성합니다.

- 다르게 설명해보면, `try...catch`는 성공하길 바라는 코드(`try` 블록)가 만약 실패하면 `catch`로 제어권을 넘겨야 할 때 사용합니다. `try` 블록의 명령문 중 하나에서 예외를 던지면, 실행 제어권은 그 즉시 `catch` 블록으로 넘어갑니다. `try` 블록 내에서 예외가 발생하지 않았으면 `catch` 블록은 실행되지 않습니다.

- 다음은 `try...catch`의 사용 모습을 보이는 예제입니다. `getMonthName()`은 매개변수의 값을 사용해 `months` 배열에서 영어 월 이름을 가져옵니다. 그런데 유효한 월(`1`-`12`) 범위의 숫자 값을 받은 것이 아니라면 `'InvalidMonthNo'`를 값으로 한 예외를 던집니다. 그러면 `catch` 블록의 명령문이 `monthName` 변수를 `'unknown'`으로 설정합니다.

```
function getMonthName(mo) {
  mo = mo - 1; // 배열 인덱스에 맞춰 월 조절 (1 = Jan, 12 = Dec)
  let months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  if (months[mo]) {
    return months[mo];
  } else {
    throw 'InvalidMonthNo'; // 여기서 throw 키워드 사용
  }
}

try {
  // 시도할 명령문
  monthName = getMonthName(myMonth); // 예외가 발생할 수 있는 함수
} catch (e) {
  monthName = 'unknown';
  logMyErrors(e); // 오류 처리기에 예외 객체 전달
}
```
